= {{ cookiecutter.project_name }}

{{ cookiecutter.project_short_description }}


== Installation

=== 1. Add submodule

Clone this theme component to your project's `themes` directory:

[source,cmd]
----
git submodule add https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug_full}} ./themes/{{cookiecutter.project_slug_full}}
----


=== 2. Add config

Add this theme component to your list of themes inside your project's `config` file (either `.yaml`, `.toml` or `.json`):

|===
| Format | Syntax

| `config.yaml`
a|
[source,yaml]
----
theme: 
  - "…"
  - "{{cookiecutter.project_slug_full}}"
  - "…"
----

| `config.toml`
a| [source,toml]
----
theme = ["…", "{{cookiecutter.project_slug_full}}", "…"]
----

| `config.json`
a| [source,json]
----
"theme": ["…", "{{cookiecutter.project_slug_full}}", "…"]
----


|===



=== 3. Embed theme component

==== Partial(s)

Include the available theme component partial(s) in your theme's template file(s):

[source,html]
----
<!-- ... -->

{% raw %}{{ if templates.Exists "partials/vendor/{% endraw %}{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}{% raw %}/include.html" }}{% endraw %}
    {% raw %}{{ partial "vendor/{% endraw %}{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}{% raw %}/include.html" . }}{% endraw %}
{% raw %}{{ end }}{% endraw %}

<!-- ... -->
----


==== Style(s)

Import the available theme component style(s) in your theme's stylesheet(s):

.`/assets/sass/my-custom-stylesheet.sass`
[source,sass]
----
// ...

@import ./vendor/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/import

// ...
----

NOTE: Stylesheets are located in the `/assets/sass` directory. If your theme's stylesheet(s) are located in a different directory, make sure to adjust the import path accordingly. For example, if your theme's styles are located in `/assets/css/my-custom-stylesheet.sass`, the import path should be `../sass/vendor/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/import`.


***

_This https://gohugo.io/hugo-modules/theme-components/[hugo theme component] was scaffolded with the https://github.com/devidw/cookiecutter-hugo-theme-component[cookiecutter-hugo-theme-component] template._